shiny:
  proxy:
    title: HMRI Surgery Audit and QI
    logo-url: https://hmri.org.au/sites/all/themes/custom/hmri/logo.png
    landing-page: /
    heartbeat-rate: 10000
    heartbeat-timeout: 60000
    port: 21001
    container-backend: kubernetes
    container-wait-time: 60000
    authentication: simple
    admin-groups: scientists, sqi-admin
    users:
    - name: user.2
      password: qi.user.2
      groups: scientists, sqi-admin, sqi-viewer
    - name: user.1
      password: qi.user.1
      groups: sqi-viewer, sqi-datagroup-1
    kubernetes:
      internal-networking: true
      url: http://localhost:8001
  apps:
  - name: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    docker-cmd: ["R", "-e shinyproxy::run_01_hello()"]
    docker-image: hmribio/combined-sp-base
    groups: scientists, mathematicians, sqi-viewer
    docker-network: bridge
    docker-label: io.rancher.container.network=true
  - name: 06_tabsets
    display-name: An app only shown to SQI-ADMIN role
    docker-cmd: ["R", "-e shinyproxy::run_06_tabsets()"]
    docker-image: hmribio/combined-sp-base
    groups: scientists, sqi-admin
    docker-network: bridge
    docker-label: io.rancher.container.network=true
  - name: Euler
    display-name: Euler App Pumped Up
    description: Testing we get the right user info
    docker-cmd: ["R", "-e shiny::runApp(\\'/root/euler\\',display.mode=\\'showcase\\')"]
    docker-image: hmribio/combined-sp-base
    groups: scientists, mathematicians, sqi-viewer
    docker-network: bridge
    docker-label: io.rancher.container.network=true
 
logging:
  level:
    # eu.openanalytics.services: DEBUG
    # org.keycloak: DEBUG
    # org.springframework.security: DEBUG
  file:
    shinyproxy.log
