shiny:
  proxy:
    title: HMRI Surgery Audit and QI
    logo-url: https://hmri.org.au/sites/all/themes/custom/hmri/logo.png
    landing-page: /
    heartbeat-rate: 10000
    heartbeat-timeout: 60000
    port: 21001
    authentication: keycloak
    admin-groups: scientists, sqi-admin
    # As per documentation on website CR 20180321
    keycloak:
      realm: surgeryqi
      auth-server-url: https://mykeycloak.bio.hmri.com.au/auth
      public-client: true
      resource: hospitapp
      credentials-secret: 8e872380-9f73-4f8e-b160-4aba951449a5
      use-resource-role-mappings: true
    # Example: 'ldap' authentication configuration
    ldap:
      url: ldap://ldap.forumsys.com:389/dc=example,dc=com
      user-dn-pattern: uid={0}
      group-search-base:
      group-search-filter: (uniqueMember={0})
      manager-dn: cn=read-only-admin,dc=example,dc=com
      manager-password: password
    # Docker configuration
    docker:
      internal-networking: true
  apps:
  - name: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    docker-cmd: ["R", "-e shinyproxy::run_01_hello()"]
    docker-image: combine-sp-base
    groups: scientists, mathematicians, sqi-viewer
    docker-network: sqi-network
  - name: 06_tabsets
    display-name: An app only shown to SQI-ADMIN role
    docker-cmd: ["R", "-e shinyproxy::run_06_tabsets()"]
    docker-image: combine-sp-base
    groups: scientists, sqi-admin
    docker-network: sqi-network
  - name: Euler
    display-name: Euler App Pumped Up
    description: Testing we get the right user info
    docker-cmd: ["R", "-e shiny::runApp('/root/euler',display.mode='showcase')"]
    docker-image: combine-sp-base
    groups: scientists, mathematicians, sqi-viewer
    docker-network: sqi-network

logging:
  level:
    # eu.openanalytics.services: DEBUG
    # org.keycloak: DEBUG
    # org.springframework.security: DEBUG
  file:
    shinyproxy.log
